apiVersion: v1
kind: Service
metadata:
  name: fastfood-api
  namespace: fiap
  labels:
    app: fastfood-api
spec:
  selector:
    app: fastfood-api  
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort