apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastfood-api
  namespace: fiap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastfood-api
  pollingInterval: 30
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: http_requests_per_second
      query: sum(rate(http_requests_received_total{exported_endpoint!~"/health|/healthz|/metrics"}[1m]))
      threshold: "5"