apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastfood-api
  namespace: fiap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastfood-api
  pollingInterval: 10
  cooldownPeriod: 15
  minReplicaCount: 2
  maxReplicaCount: 8
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 100
              periodSeconds: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: http_requests_per_second
      query: sum(rate(http_requests_received_total{exported_endpoint!~"/health|/healthz|/metrics"}[30s]))
      threshold: "20"