name: pipeline-api-dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet_build_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
           
  build_push_image:
    runs-on: ubuntu-latest
    needs: dotnet_build_and_tests
    environment: prd

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Create image tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            VERSION="pr-${{ github.event.pull_request.number }}"
          else
            VERSION="latest"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_TENANT }}/fiap-soat-fastfood-api:latest
            ${{ secrets.DOCKERHUB_TENANT }}/fiap-soat-fastfood-api:${{ steps.vars.outputs.version }}