name: pipeline-api-dotnet

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet_build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal

  build_push_image:
    runs-on: ubuntu-latest
    needs: dotnet_build
    environment: prd

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Create image tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            VERSION="pr-${{ github.event.pull_request.number }}"
          else
            VERSION="latest"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_TENANT }}/fiap-soat-fastfood-api:${{ steps.vars.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image
    environment: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Settings
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Install kubectl and kubelogin
        run: |
          az aks install-cli
          kubelogin --version

      - name: Get AKS Kubeconfig
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Create secrets manifest
        run: |
          cat > ./k8s/fastfood-api-secret.yaml <<'EOF'
          ${{ secrets.API_SECRETS_MANIFEST }}
          EOF

      - name: Set image version (PR only)
        if: github.event_name == 'pull_request'
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_TENANT }}/fiap-soat-fastfood-api:${{ env.VERSION }}|g" k8s/fastfood-api-deployment.yaml

      - name: Deploy
        run: |
          kubectl apply -f k8s/.
          kubectl rollout status deployment/fastfood-api -n fiap
